# Tasks for configuring network interfaces on Ubuntu
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Getting interfaces infos
  interfaces_file:
  register: cur_interfaces
  when: is_host_to_be_modified

- name: Setting facts for network interfaces
  set_fact:
    primary_dhcp_net_itf: "{% set sel = [] %}{% for k,v in cur_interfaces.get('ifaces', {}).iteritems() %}{% if v.get('method') == 'dhcp' and hostvars[inventory_hostname]['ansible_' + k | replace('-', '_') ]['ipv4']['address'] is match(hostvars[inventory_hostname]['ip_prefix'] + '.*') %}{% set l = sel.append(k) %}{% endif %}{% endfor %}{{ sel }}"
    secondary_dhcp_net_itfs: "{% set sel = [] %}{% for k,v in cur_interfaces.get('ifaces', {}).iteritems() %}{% if v.get('method') == 'dhcp' and not hostvars[inventory_hostname]['ansible_' + k | replace('-', '_') ]['ipv4']['address'] is match(hostvars[inventory_hostname]['ip_prefix'] + '.*') %}{% set l = sel.append(k) %}{% endif %}{% endfor %}{{ sel }}"
    non_dhcp_net_itfs: "{% set sel = [] %}{% for k,v in cur_interfaces.get('ifaces', {}).iteritems() %}{% if v.get('method') != 'dhcp' %}{% set l = sel.append(k) %}{% endif %}{% endfor %}{{ sel }}"
  when: is_host_to_be_modified

- name: Setting facts for VLANs network interfaces
  set_fact:
    mgmt_net_itf: "{{ primary_dhcp_net_itf[0] }}"
  when: is_host_to_be_modified and primary_dhcp_net_itf | length > 0

- name: Setting facts for VLANs network interfaces
  set_fact:
    storage_net_itf: "{{ secondary_dhcp_net_itfs[0] }}"
    vxlan_net_itf: "{{ secondary_dhcp_net_itfs[0] }}"
    vlan_net_itf: "{{ secondary_dhcp_net_itfs[0] }}"
  when: is_host_to_be_modified and secondary_dhcp_net_itfs | length > 0

- name: Moving non-dhcp and primary interfaces to their own config file
  interfaces_file:
    src: /etc/network/interfaces
    dest: "/etc/network/interfaces.d/{{ item }}.cfg"
    iface: "{{ item }}"
    state: move
  register: itfs_changed
  when: is_host_to_be_modified
  with_items: "{{ non_dhcp_net_itfs + primary_dhcp_net_itf }}"

- name: Moving secondary ethernet interfaces to their own config file and update them from dhcp to manual
  interfaces_file:
    src: /etc/network/interfaces
    dest: "/etc/network/interfaces.d/{{ item }}.cfg"
    iface: "{{ item }}"
    state: move
    method: manual
  register: secondary_changed
  when: is_host_to_be_modified
  with_items: "{{ secondary_dhcp_net_itfs }}"

- name: Including bridges and vlans variables file
  include_vars:
    file: ../vars/osa-briges-vlans_vars.yml
  when: is_host_to_be_modified

- name: Configuring {{ primary_dhcp_net_itf[0] }} VLANs and bridges
  template:
    src: "{{ role_path }}/templates/bridge_vlans_itf_cfg-ubuntu.j2"
    dest: "/etc/network/interfaces.d/{{ primary_dhcp_net_itf[0] }}.cfg"
    owner: root
    group: root
    mode: 0644
  register: primary_vlan_changed
  when: is_host_to_be_modified and primary_dhcp_net_itf | length > 0 and (not is_aio or (force_networking | default(false) | bool))
  vars:
    - prov_itf: "{{ primary_dhcp_net_itf[0] }}"
    - prov_itf_mode: dhcp
    - vlans_list: "{{ osa_vlans | default([]) }}"
    - ip_suffix: "{{ ansible_host.split('.')[-1] }}"
    - node_roles: "{{ hostvars.get('infra-master', {}).get('osa_nodes_roles', {}).get(inventory_hostname, []) }}"

- name: Configuring {{ secondary_dhcp_net_itfs[0] }} VLANs and bridges
  template:
    src: "{{ role_path }}/templates/bridge_vlans_itf_cfg-ubuntu.j2"
    dest: "/etc/network/interfaces.d/{{ secondary_dhcp_net_itfs[0] }}.cfg"
    owner: root
    group: root
    mode: 0644
  register: secondary_vlan_changed
  when: is_host_to_be_modified and secondary_dhcp_net_itfs | length > 0 and (not is_aio or (force_networking | default(false) | bool))
  vars:
    - prov_itf: "{{ secondary_dhcp_net_itfs[0] }}"
    - vlans_list: "{{ osa_vlans | default([]) }}"
    - ip_suffix: "{{ ansible_host.split('.')[-1] }}"
    - node_roles: "{{ hostvars.get('infra-master', {}).get('osa_nodes_roles', {}).get(inventory_hostname, []) }}"

- name: Set fact for conditional execution
  set_fact:
    network_reconfig: True
  when: ((itfs_changed is defined and itfs_changed.changed) or
         (secondary_changed is defined and secondary_changed.changed) or
         (primary_vlan_changed is defined and primary_vlan_changed.changed) or
         (secondary_vlan_changed is defined and secondary_vlan_changed.changed))

- name: Disabling existing services for DIB dhcp-all-interfaces
  shell: systemctl list-unit-files | grep dhcp-interface | sed -e 's/^.*dhcp/dhcp/' | sed -e 's/  *.*//' -e 's/^/systemctl disable -q --force /' | bash
  ignore_errors: true
  changed_when: false
  when: is_host_to_be_modified

- name: Disabling existing services for DIB dhcp-all-interfaces
  shell: systemctl list-units | grep dhcp-interface | sed -e 's/^.*dhcp/dhcp/' | sed -e 's/  *.*//' -e 's/^/systemctl disable -q --force /' | bash
  ignore_errors: true
  changed_when: false
  when: is_host_to_be_modified

- name: Stopping existing services for DIB dhcp-all-interfaces
  shell: systemctl list-units | grep dhcp-interface | sed -e 's/^.*dhcp/dhcp/' | sed -e 's/  *.*//' -e 's/^/systemctl stop -q --force /' | bash
  ignore_errors: true
  changed_when: false
  when: is_host_to_be_modified

- name: Removing DIB dhcp-all-interfaces udev item {{ item }}
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/systemd/system/dhcp-interface@.service
    - /etc/udev/rules.d/99-dhcp-all-interfaces.rules
    - /usr/local/sbin/dhcp-all-interfaces.sh
  register: removed_udev_rules
  when: is_host_to_be_modified

- name: Restarting udev service
  shell: "udevadm control --reload-rules && udevadm trigger"
  when: is_host_to_be_modified and removed_udev_rules is changed

- name: Rebooting nodes
  shell: echo "reboot" | at now + 0 min
  when: is_host_to_be_modified and network_reconfig is defined and network_reconfig

- name: Waiting for nodes to be reachable again by SSH
  wait_for: >
    host="{{ hostvars.get(inventory_hostname, {}).get('ansible_host') }}"
    port=22
    delay=10
    timeout=3600
    sleep=20
    connect_timeout=10
    search_regex=OpenSSH
  delegate_to: localhost
  become: no
  when: network_reconfig is defined and network_reconfig
