# Bifrost OSA nodes mandatory packages for CentOS
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

systempkgs: "{{
  system +
  dev +
  disk +
  monitoring +
  network +
  proxy +
  python +
  user +
  virtualization
  }}"

system:
  - acl
  - acpid
  - at
  - sshpass
  - sed
  - tar
  - unzip
  - util-linux

dev:
  - autoconf
  - bash
  - coreutils
  - diffutils
  - findutils
  - gawk
  - gcc
  - gcc-c++
  - git
  - glibc-devel
  - grep
  - kernel-headers
  - libselinux-devel
  - openssl-devel
  - pcre-devel
  - python-devel
  - systemd-devel
  - zlib-devel

disk:
  - btrfs-progs
  - cryptsetup
  - e2fsprogs
  - gdisk
  - mdadm
  - parted
  - squashfs-tools
  - xfsprogs

monitoring:
  - arpwatch
  - dstat
  - iotop
  - iptraf-ng
  - nmap
  - sysstat
  - wireshark

network:
  - bridge-utils
  - ethtool
  - iputils
  - iscsi-initiator-utils
  - nc
  - ntp
  - ntpdate
  - openssh-server

proxy:
  - socat

python:
  - python-virtualenv

user:
  - screen
  - tmux
  - tree
  - vim

virtualization:
  - libvirt-daemon-lxc
  - open-vm-tools
  - virt-what

prohibited_systempkgs:
  - centos-openstack-release-*
  - centos-release-ceph-jewel
  - centos-release-qemu-ev
  - centos-release-storage-common
