---
# Bifrost master node IP configuration
ip_prefix: 10.20.30
ip_suffix: 1
ip_netmask: 255.255.255.0
ip_netmask_bits: 24
ip_netmask_broadcast: 255
# User which will be used for Ansible communication
# and whose home will be retrieving and storing the
# various Git repos
systemuser: "{{ ansible_user | default(vagrant) }}"
systempasswd: "{{ ansible_user | default(vagrant) }}"
dhcptimeout: "{{ dhcp_timeout | default(10) }}"
libvirtgroup: "{{ libvirt_group | default('libvirtd') }}"
