# OpenNext nodes bridges and VLANs configuration
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

opennext_vlans: [
  {
    name: "prov",
    vlan_comment: "vlan {{ prov_vlan_id | default('111') }} - infrastructure provisioning network",
    id: "{{ prov_vlan_id | default('111') }}",
    bridge_comment: "bridge br-prov - infrastructure provisioning network",
    prefix: "{{ ip_prefix | default('20.20.20') }}",
    netmask: "{{ ip_netmask | default('255.255.255.0') }}",
  },
]
opennext_bridges: [
]
