# OSA nodes bridges and VLANs configuration
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

osa_vlans: [
  {
    name: "mgmt",
    vlan_comment: "vlan 10 - management network",
    id: 10,
    bridge_comment: "bridge br-mgmt - management network",
    prefix: "172.29.236",
    netmask: "255.255.252.0",
# Setting the following will potentially make the specified address
# default gateway for the entire platform.
# Commenting it out to avoid this.
#    gateway: "172.29.236.1",
    roles: [
      { name: "compute", assign_address: True },
      { name: "control", assign_address: True },
      { name: "infra-master", assign_address: True },
      { name: "osa-master", assign_address: True },
      { name: "storage", assign_address: True },
    ],
    interface: "{{ mgmt_net_itf | default('eth0') }}",
  },
  {
    name: "storage",
    vlan_comment: "vlan 20 - storage network",
    id: 20,
    bridge_comment: "bridge br-storage - storage network",
    prefix: "172.29.244",
    netmask: "255.255.252.0",
    roles: [
      { name: "compute", assign_address: True },
      { name: "control", assign_address: False },
      { name: "storage", assign_address: True },
    ],
    interface: "{{ storage_net_itf | default('eth1') }}",
  },
  {
    name: "vxlan",
    vlan_comment: "vlan 30 - vxlan network",
    id: 30,
    bridge_comment: "bridge br-vxlan - vxlan network",
    prefix: "172.29.240",
    netmask: "255.255.252.0",
    roles: [
      { name: "compute", assign_address: True },
      { name: "control", assign_address: False },
      { name: "network", assign_address: True },
    ],
    interface: "{{ vxlan_net_itf | default('eth1') }}",
  },
  {
    name: "vlan",
    bridge_comment: "bridge br-vlan - vlan network",
    bridge_veth: "veth",
    bridge_veth_itf: "eth12",
    prefix: "172.29.248",
    netmask: "255.255.252.0",
    roles: [
      { name: "compute", assign_address: True },
      { name: "control", assign_address: False },
    ],
    interface: "{{ vlan_net_itf | default('eth1') }}",
  },
]
