# OSA disks and partitions configuration
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

osa_disks: [
    {
      device_path: "{{ base_system_disk_device | default('/dev/sda') }}",
      # The min size should be at least the sum of all partitions
      # defined hereafter
      minsize: 720.0,
      partitions: [
          {
            name: "openstack-core",
            vg: "os-",
            lv: "core",
            size: "{{ base_partition_size | default(100.0) | float }}",
            mountpoint: "/openstack",
          },
          {
            name: "openstack-logs",
            vg: "os-",
            lv: "logs",
            size: "{{ base_partition_size | default(100.0) | float }}",
            mountpoint: "/openstack/log",
          },
          {
            name: "openstack-varliblxc",
            vg: "os-",
            lv: "lxc",
            size: "{{ base_partition_size | default(100.0) | float }}",
            mountpoint: "/var/lib/lxc",
          },
          {
            name: "swap",
            vg: "os-",
            lv: "swap",
            size: "{{ base_swap_partition_size | default(16.0) | float }}",
            type: "swap",
            fstype: "ext4",
          },
          {
            name: "cinder-volumes",
            vg: "cinder-volumes",
            size: "{{ base_partition_size | default(200.0) | float }}",
            type: "vgonly",
            roles: [
              { "storage": True },
            ],
          },
          {
            name: "openstack-novainstances",
            vg: "os-",
            lv: "nova",
            size: "{{ base_partition_size | default(200.0) | float }}",
            mountpoint: "/var/lib/nova/instances",
            roles: [
              { "compute": True },
            ],
          },
       ],
    },
]
