---
# OSA nodes bridges and VLANs configuration
physical_itf: eth0
mgmt_vlan_id: 10
vxlan_vlan_id: 30
storage_vlan_id: 20
mgmt_ip_prefix: 172.29.236
vxlan_ip_prefix: 172.29.240
storage_ip_prefix: 172.29.244
ip_suffix: 1
netmask: 255.255.252.0
gateway: "{{ mgmt_ip_prefix }}.1"
dns_servers: "8.8.8.8 8.8.4.4"
