# Tasks for configuring SSH
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setting proper perms on {{ systemuser }} .ssh
  file:
    path: "{{ systemuserhome }}/.ssh"
    mode: 0700
    owner: "{{ systemuser }}"
    group: "{{ systemuser }}"
    state: directory
  when: is_host_to_be_modified

- name: Creating root .ssh
  file:
    path: "{{ root_ssh_dir }}"
    mode: 0700
    owner: "root"
    group: "root"
    state: directory
  when: is_host_to_be_modified

- name: Configuring SSH defaults for root
  template:
    src: ../templates/ssh_cfg.j2
    dest: "{{ root_ssh_dir }}/config"
    owner: "root"
    group: "root"
    mode: 0644
  vars:
    ips: "{{ hostvars.get('infra-master', {}).get('osa_nodes_ips', []) }}"
    vlans: "{{ all_vlans_ips }}"
  when: is_host_to_be_modified

- name: Copy {{ systemuser }} private SSH key file to root
  copy:
    src: "{{ lookup('fileglob', systemuserhome + '/.ssh/id_rsa') }}"
    dest: "{{ root_ssh_dir }}"
    owner: "root"
    group: "root"
    mode: 0600
  when: is_host_to_be_modified

- name: Copy {{ systemuser }} public SSH key file to root from {{ systemuserhome }})
  copy:
    src: "{{ lookup('fileglob', systemuserhome + '/.ssh/id_rsa.pub') }}"
    dest: "{{ root_ssh_dir }}"
    owner: "root"
    group: "root"
    mode: 0644
  when: is_host_to_be_modified

- name: Copy {{ systemuser }} authorized keys file to root from {{ systemuserhome }})
  copy:
    src: "{{ lookup('fileglob', systemuserhome + '/.ssh/authorized_keys') }}"
    dest: "{{ root_ssh_dir }}"
    owner: "root"
    group: "root"
    mode: 0644
  when: is_host_to_be_modified

- name: Configuring SSH defaults for {{ systemuser }}
  template:
    src: ../templates/ssh_cfg.j2
    dest: "{{ systemuserhome }}/.ssh/config"
    owner: "{{ systemuser }}"
    group: "{{ systemuser }}"
    mode: 0644
  vars:
    ips: "{{ hostvars.get('infra-master', {}).get('osa_nodes_ips', []) }}"
    vlans: "{{ all_vlans_ips }}"
  when: is_host_to_be_modified

- name: Copy {{ systemuser }} private SSH key file
  copy:
    src: "{{ lookup('fileglob', systemuserhome + '/.ssh/id_rsa') }}"
    dest: "{{ systemuserhome }}/.ssh"
    owner: "{{ systemuser }}"
    group: "{{ systemuser }}"
    mode: 0600
  when: is_host_to_be_modified

- name: Copy {{ systemuser }} public SSH key file
  copy:
    src: "{{ lookup('fileglob', systemuserhome + '/.ssh/id_rsa.pub') }}"
    dest: "{{ systemuserhome }}/.ssh"
    owner: "{{ systemuser }}"
    group: "{{ systemuser }}"
    mode: 0644
  when: is_host_to_be_modified
