---
- hosts: infra-master
  become: yes

  vars_files:
    - ../vars/infra-master-configure-system_vars.yml

  tasks:

    - name: Setting Facts
      set_fact:
        root_ssh_dir: "{{ root_dot_ssh_dir | default('/root/.ssh') }}"
        dest_repo_dir: "{{ dest_github_repo_dir | default('/opt') }}"

    - name: Creating root .ssh
      file:
            path: "{{ root_ssh_dir }}"
            mode: 0700
            owner: "root"
            group: "root"
            state: directory

    - include_tasks: ../tasks/clone_private_git_repo.yml
      vars:
        repo: "{{ item.repo }}"
        repodst: "{{ item.get('repodst', '') }}"
        sshdir: "{{ root_ssh_dir }}"
        destdir: "{{ dest_repo_dir }}"
      with_items:
        - { repo: "openstack-ansible-bootstrap", repodst: "onpc-bootstrap"}

    - name: Installing Squid proxy package
      package:
        name: squid
        state: latest

  roles:
    - role: kbrebanov.squid
      squid_tcp_outgoing_address: "{{ ansible_default_ipv4.address }}"
      squid_acls:
        - { name: "allowed_ips", type: "src", argument: "{{ ip_prefix | default('20.20.20') }}.0/{{ ip_netmask_bits | default(24) }}" }
        - { name: "SSL_ports", type: "port", argument: "22" }
        - { name: "Safe_ports", type: "port", argument: "22" }
      squid_http_access_allow_clients:
        - localhost
        - allowed_ips
