---
- hosts: infra-master
  become: no

  vars_files:
    - ../vars/infra-master-configure-system_vars.yml
    - ../vars/infra-master-deploy-bifrost_vars.yml

  tasks:

    - import_tasks: ../tasks/operational_informations.yml

- hosts: kvm-master
  become: no

  tasks:

    - include_tasks: ../tasks/kvm_vm_create.yml
      vars:
        vmname: "{{ vm_item.name }}"
        vmcpus: "{{ vm_item.cpus }}"
        vmmemorysizegb: "{{ vm_item.mem }}"
        vmdisksizegb: "{{ vm_item.hdd }}"
        vncport: "{{ vm_item.vnc }}"
        vbmc_port: "{{ vm_item.bmc }}"
        vmmacprefix: "52:54:01"
      with_items:
        - { name: "slave-1", cpus: 4, mem: 16, hdd: 60, vnc: 5901, bmc: 6001}
        - { name: "slave-2", cpus: 4, mem: 16, hdd: 60, vnc: 5902, bmc: 6002}
        - { name: "slave-3", cpus: 4, mem: 16, hdd: 60, vnc: 5903, bmc: 6003}
      loop_control:
        loop_var: vm_item

- hosts: infra-master
  become: no

  vars_files:
    - ../vars/infra-master-configure-system_vars.yml
    - ../vars/infra-master-deploy-bifrost_vars.yml

  tasks:

    - import_tasks: ../tasks/vm_get_status.yml

    - name: Extracting VMs names from facts
      set_fact:
        vm_names: "{{ hostvars[inventory_hostname].registered_status.json | json_query('keys(@)') }}"
        vm_ips: "{{ hostvars[inventory_hostname].registered_status.json | json_query('values(@)') | map(attribute='extra/all/interfaces/eth0/ip') | list }}"

    - name: Waiting for VMs to be reachable by SSH
      wait_for:
        sleep: 60
        timeout: 3600
        port: 22
        host: '{{ item }}'
        search_regex: OpenSSH
      with_items: "{{ vm_ips }}"

    - name: Creating OSA inventory file
      template:
        src: ../templates/inventory.cfg.j2
        dest: "{{ systemuserhome }}/osa-inventory"
      vars:
        infra_master_ip: "{{ hostvars[inventory_hostname].ansible_br_host.ipv4.address }}"
        osa_master_ip: "{{ hostvars[inventory_hostname].registered_status.json.get(vm_names[0]).get('extra/all/interfaces/eth0/ip') }}"
        osa_vms: "{{ vm_names }}"
