---
- hosts: infra-master
  become: no

  vars_files:
    - ../vars/infra-master-configure-system_vars.yml
    - ../vars//infra-master-deploy-bifrost_vars.yml

  tasks:

    - import_tasks: ../tasks/operational_informations.yml

    - include_tasks: ../tasks/kvm_vm_create.yml
      vars:
        vmname: osa-aio
        vmcpus: 10
        vmmemorysizegb: 48
        vmdisksizegb: 120
        vmdisksnb: 2
        vmmacprefix: "52:54:00"

    - import_tasks: ../tasks/vm_get_status.yml

    - name: Extracting VMs names from facts
      set_fact:
        vm_names: "{{ hostvars[inventory_hostname].registered_status.json | json_query('keys(@)') }}"
        vm_ips: "{{ hostvars[inventory_hostname].registered_status.json | json_query('values(@)') | map(attribute='extra/all/interfaces/eth0/ip') | list }}"

    - name: Waiting for VMs to be reachable by SSH
      wait_for:
        sleep: 60
        timeout: 3600
        port: 22
        host: '{{ item }}'
        search_regex: OpenSSH
      with_items: "{{ vm_ips }}"

    - name: Creating OSA inventory file
      template:
        src: ../templates/inventory.cfg.j2
        dest: "{{ systemuserhome }}/osa-inventory"
      vars:
        infra_master_ip: "{{ hostvars[inventory_hostname].ansible_br_host.ipv4.address }}"
        osa_master_ip: "{{ hostvars[inventory_hostname].registered_status.json.get(vm_names[0]).get('extra/all/interfaces/eth0/ip') }}"
        osa_vms: "{{ vm_names }}"
