---
- hosts: master
  become: no

  vars_files:
    - ../vars/master-configure-system_vars.yml
    - ../vars/master-deploy-bifrost_vars.yml

  tasks:

    - name: Retrieving Bifrost GitHub Repository
      git:
        repo: https://github.com/obourdon/bifrost
        dest: "{{ git }}"

    - name: Creating Bifrost Virtualenv Directory
      file:
        path: "{{ venv }}"
        owner: "{{ systemuser }}"
        group: "{{ systemuser }}"
        mode: 0755
        state: directory

    - name: Setting Up Bifrost Environment
      command: "./scripts/env-setup.sh"
      args:
        chdir: "{{ git }}"
        creates: "{{ venv }}/bin/activate"
      environment:
        LC_ALL: C
        VENV: "{{ venv }}"
        https_proxy: ""
      register: setup_result

    - name: Getting Setup Result
      set_fact:
        todo: "{{ setup_result.stdout.split('\n')[-3:-1] | join(' && ') | replace('source','.') | replace('env-vars','../env-vars') }}"
        dib_std_options: " -e dib_init_element=dhcp-all-interfaces -e dib_image_type=bootloader -e extra_dib_elements=dracut-regenerate,devuser,cloud-init-nocloud,openssh-server -e dib_packages=python,python3-yaml,dracut,dnsutils,net-tools,netcat,dnsutils,iputils-ping,traceroute"

    - name: Set partitioning informations
      set_fact:
        dib_partitioning_infos: " -e partitioning_file={{ systemuserhome }}/{{ partitioning_scheme }}.yml"
      when: partitioning_scheme is defined and partitioning_scheme | length > 0

    - name: Computing OS Image Options
      set_fact:
        os_opts: "{{ dib_std_options | default('') }}{{ dib_partitioning_infos | default('') }} -e dib_imagesize={{ root_part_size_gb | default(60) }} -e dib_os_release={{ os_release | default('xenial') }} -e dib_os_element={{ os_flavor | default('ubuntu-minimal') }} -e ipa_upstream_release={{ upstream_release | default('stable-pike') }}"
        opennext_opts: " -e use_symlinks=true"

    - name: Computing Keystone Options
      set_fact:
        keystone_opts: " -e enable_keystone=true -e noauth_mode=false"
      when: keystone

    - import_tasks: ../tasks/secondary_network_interface.yml

    - import_tasks: ../tasks/select_secondary_network_interface.yml
      vars:
       itf_state: true

    - name: Retrieving all deploy options
      set_fact:
        all_args: "-e network_interface={{ itf }}{{ keystone_opts }}{{ os_opts }}{{ opennext_opts }}"
        args_file: "{{ systemuserhome }}/deploy_args.yml"

    - name: Populating remote configuration file
      template:
        src: ../templates/extra_deployment_args.j2
        dest: "{{ args_file }}"
        owner: "{{ systemuser }}"
        group: "{{ systemuser }}"
        mode: 0644
      vars:
        args: "{{ all_args.split(' ') | reject('equalto', '-e') | list }}"

    - name: Printing complete deploy command
      debug: msg="ssh {{ systemuser }}@{{ ansible_default_ipv4.address }} -t 'cd {{ git }}/playbooks && {{ todo }} && https_proxy= ansible-playbook -i inventory/target install.yaml {{ all_args }}'"

    - name: Printing alternate (shorter) deploy command
      debug: msg="ssh {{ systemuser }}@{{ ansible_default_ipv4.address }} -t 'cd {{ git }}/playbooks && {{ todo }} && https_proxy= ansible-playbook -i inventory/target install.yaml -e @{{ args_file }}'"

    - name: Running Bifrost Playbook
      shell: ". ../env-vars && . {{ venv }}/bin/activate && ansible-playbook -i inventory/target install.yaml {{ all_args }}"
      args:
        chdir: "{{ git }}/playbooks"
      environment:
        LC_ALL: C
        VENV: "{{ venv }}"
        https_proxy: ""
      when: todo is undefined
