---
- hosts: osa-master
  become: yes

  tasks:

    - name: Setting Facts
      set_fact:
        root_ssh_dir: "{{ root_dot_ssh_dir | default('/root/.ssh') }}"
        dest_repo_dir: "{{ dest_github_repo_dir | default('/opt') }}"

    - name: Retrieving OSA GitHub Repository
      git:
        repo: "https://github.com/obourdon/openstack-ansible"
        dest: "{{ dest_repo_dir }}/openstack-ansible"
        accept_hostkey: yes
        force: yes
        recursive: no
        version: stable/pike

    - include_tasks: ../tasks/clone_private_git_repo.yml
      vars:
        repo: "{{ item.repo }}"
        repodst: "{{ item.get('repodst', '') }}"
        sshdir: "{{ root_ssh_dir }}"
        destdir: "{{ dest_repo_dir }}"
        gitenv:
          TMPDIR: "/var/tmp"
      with_items:
        - { repo: "onpc-basic-model" }
        - { repo: "onpc-monitoring" }

    - name: Boostrapping Ansible for OSA
      command: "./scripts/bootstrap-ansible.sh"
      args:
        chdir: "/opt/openstack-ansible"
        creates: "/opt/ansible-runtime/bin/ansible-playbook"
      environment:
        TMPDIR: "/var/tmp"
      register: bootstrap_ansible_result

    - name: Boostrapping AIO for OSA
      command: "./scripts/bootstrap-aio.sh"
      args:
        chdir: "/opt/openstack-ansible"
        creates: "/etc/openstack_deploy/user_variables.yml"
        # Could also be /etc/network/interfaces.d/osa_interfaces.cfg
      environment:
        TMPDIR: "/var/tmp"
        BOOTSTRAP_OPTS: "bootstrap_host_data_disk_device=vdb" 
      register: bootstrap_aio_result
      when: hostvars.get('infra-master', {}).get('groups', {}).get('osa-vms', []) | length == 1
      # Could also be osa-master instead of infra-master
