# DIB dhcp-all-interfaces services cleanup/removal task
---
- name: Disabling existing services for DIB dhcp-all-interfaces
  shell: systemctl list-unit-files | grep dhcp-interface | sed -e 's/^.*dhcp/dhcp/' | sed -e 's/  *.*//' -e 's/^/systemctl disable -q --force /' | bash
  ignore_errors: true
  changed_when: false

- name: Disabling existing services for DIB dhcp-all-interfaces
  shell: systemctl list-units | grep dhcp-interface | sed -e 's/^.*dhcp/dhcp/' | sed -e 's/  *.*//' -e 's/^/systemctl disable -q --force /' | bash
  ignore_errors: true
  changed_when: false

- name: Stopping existing services for DIB dhcp-all-interfaces
  shell: systemctl list-units | grep dhcp-interface | sed -e 's/^.*dhcp/dhcp/' | sed -e 's/  *.*//' -e 's/^/systemctl stop -q --force /' | bash
  ignore_errors: true
  changed_when: false

- name: Removing DIB dhcp-all-interfaces udev item {{ item }}
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/systemd/system/dhcp-interface@.service
    - /etc/udev/rules.d/99-dhcp-all-interfaces.rules
    - /usr/local/sbin/dhcp-all-interfaces.sh
  register: removed_udev_rules

- name: Restarting udev service
  shell: udevadm control --reload-rules && udevadm trigger
  when: removed_udev_rules is changed
