# Private GitHub repository cloning task
---
- name: Setting Fact for {{ repo }}
  set_fact:
    repo_key_filename: "opennext_{{ repo }}_git_deploykey"
    final_dst: "{{ repodst | default(repo) }}"

- name: Preventing empty destination path
  set_fact:
    final_dst: "{{ repo }}"
  when: final_dst | length == 0

- name: Uploading Github DeployKey for {{ repo }}
  copy:
    src: "../files/ssh-keys/{{ key_item.filename }}"
    dest: "{{ sshdir }}/{{ key_item.filename }}"
    mode: "{{ key_item.mode }}"
    owner: "root"
    group: "root"
  with_items:
    - { filename: "{{ repo_key_filename }}.pub", mode: '0644' }
    - { filename: "{{ repo_key_filename }}", mode: '0600' }
  loop_control:
    loop_var: key_item

- name: Retrieving OpenNext {{ repo }} GitHub Repository
  git:
    repo: "git@github.com:opennext-io/{{ repo }}"
    dest: "{{ destdir }}/{{ final_dst }}"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ sshdir }}/{{ repo_key_filename }}"
  environment: "{{ gitenv | default('{}') }}"
