# Linux kernel drivers/modules configuration task
---
# Add the specified module into configuration
- name: Configuring system module {{ module }}
  lineinfile:
    path: /etc/modules
    line: "{{ module }}"
    state: present
    owner: root
    group: root
    mode: 0644

# Add the specified module into running system
- name: Loading system module {{ module }}
  modprobe:
    name: "{{ module }}"
    state: present
