# KVM/libvirt disk creation task
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Getting pool informations from KVM/libvirt
  virt_pool:
    command: list_pools
  register: pools_xml_infos_result

- name: Creating default pool for KVM/libvirt
  virt_pool:
    command: define
    name: default
    xml: '{{ lookup("template", "../templates/kvm-pool.xml.j2") }}'
  vars:
    uuid_seed: "OpenNext"

- name: Creating pool directory for KVM/libvirt
  become: yes
  file:
    path: "{{ pool_path | default('/var/lib/libvirt/images') }}"
    state: directory
    owner: root
    group: root
    mode: 0711

- name: Activating default pool for KVM/libvirt
  virt_pool:
    command: create
    name: default
    state: active

- name: Autostarting default pool for KVM/libvirt
  virt_pool:
    name: default
    autostart: yes

- name: Getting default pool informations from KVM/libvirt
  virt_pool:
    name: "default"
    command: get_xml
  register: default_pool_xml_infos_result

- name: Getting path for default pool for KVM/libvirt
  block:

    - name: Parsing XML using XPATH to get path for default pool for KVM/libvirt
      xml:
        xmlstring: "{{ default_pool_xml_infos_result.get('get_xml', '') }}"
        xpath: '//target/path'
        content: text
      register: default_pool_path_infos

    - name: Storing XML parsing result in fact for path for default pool for KVM/libvirt
      set_fact:
        kvm_vms_disks_path: "{{ default_pool_path_infos.get('matches', [])[0].get('path', '') }}"

- fail: msg="Unable to retrieve default pool path for KVM/libvirt"
  when: kvm_vms_disks_path | length == 0

- name: Checking existence of {{ diskname }} for {{ vmname }}
  command: "virsh vol-list --pool default"
  changed_when: false
  register: vol_list

- name: Setting fact for disk name
  set_fact:
    cur_disk_name: "{{ vmname }}-{{ diskname }}.qcow2"

- name: Creating {{ diskname }} for {{ vmname }}
  command: "virsh vol-create-as --pool default --name {{ cur_disk_name }} --capacity {{ vmdisksizegb }}G --format qcow2"
  when: vol_list.stdout_lines | select('match', '^ ' + cur_disk_name + ' ') | list | length == 0

- name: Retrieving infos on {{ diskname }} for {{ vmname }}
  command: "virsh vol-list --pool default"
  changed_when: false
  register: vol_list

- fail: msg="Error retrieving {{ diskname }} for {{ vmname }} in default pool for KVM/libvirt"
  when: vol_list.stdout_lines | select('match', '^ ' + cur_disk_name + ' ') | list | length != 1

- name: Setting fact for storing path of created volume for {{ diskname }} for {{ vmname }}
  set_fact:
    vm_disks_paths: "{% set l = vmdiskspaths.append(vol_list.stdout_lines | select('match', '^ ' + cur_disk_name + ' ') | map('regex_replace', '^ .*  */', '/') | list | first) %}{{ vmdiskspaths | list }}"
