# KVM/libvirt host configuration task
---
- name: Adding existing user {{ systemuser }} to group {{ libvirtgroup }}
  user:
    name="{{ systemuser }}"
    groups="{{ libvirtgroup }}"
    append=yes

- name: Making sure libvirt service is running
  service:
    name: "{{ libvirtservice }}"
    state: started

# Facts will be available as 'ansible_libvirt_networks'
- name: Gather facts about available networks in KVM/libvirt
  virt_net:
    command: facts

- name: Creating KVM/libvirt network bridge template & network
  block:

    - name: Creating KVM/libvirt network bridge template & network
      become: no
      template:
        src: ../templates/kvm-network-bridge.xml.j2
        dest: "{{ systemuserhome }}/kvm-provisioning-network-bridge.xml"
        owner: "{{ systemuser }}"
        group: "{{ systemuser }}"
        mode: 0644
      vars:
        network_name: "{{ kvm_network_name }}"
        bridge_interface: "{{ kvm_bridge_itf }}"
        uuid_seed: "OpenNext"

    - name: Getting XML definition of KVM/libvirt network
      slurp:
        src: "{{ systemuserhome }}/kvm-provisioning-network-bridge.xml"
      register: xml_network

    - name: Creating KVM/libvirt network
      virt_net:
        command: define
        name: "{{ kvm_network_name }}"
        xml: "{{ xml_network['content'] | b64decode }}"
  when: ansible_libvirt_networks is defined and kvm_network_name not in ansible_libvirt_networks

- name: Autostarting KVM/libvirt network
  virt_net:
    autostart: yes
    name: "{{ kvm_network_name }}"

- name: Activating KVM/libvirt network
  virt_net:
    state: active
    name: "{{ kvm_network_name }}"

- name: Retrieving max free space mount point
  set_fact:
    max_free_mount: "{{ ansible_mounts | sort('size_available' | int) | last }}"

- name: Setting {{ libvirtvarpath }} destination to max free space zone
  set_fact:
    virt_dest: "{{ max_free_mount['mount'] }}"

- name: Getting filesystem informations about {{ libvirtvarpath }}
  stat:
    path: "{{ item }}"
    follow: yes
  register: libvirt_stat
  with_items:
    - "{{ libvirtvarpath }}"
    - "{{ virt_dest }}"

- name: Migrating {{ libvirtvarpath }} to {{ virt_dest }}
  block:

    - name: Stopping libvirt service
      service:
        name: "{{ libvirtservice }}"
        state: stopped

    - name: Moving over {{ libvirtvarpath }} to {{ virt_dest }}
      command: "mv {{ libvirtvarpath }} {{ virt_dest }}"

    - name: Re-creating {{ libvirtvarpath }} directory
      file:
        path: "{{ libvirtvarpath }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Bindmounting {{ virt_dest | regex_replace('/$', '') }}/{{ libvirtvarpath | basename }} onto {{ libvirtvarpath }}
      mount:
        path: "{{ libvirtvarpath }}"
        src: "{{ virt_dest | regex_replace('/$', '') }}/{{ libvirtvarpath | basename }}"
        opts: bind
        fstype: none
        state: mounted

    - name: Restarting libvirt service
      service:
        name: "{{ libvirtservice }}"
        state: started
  when: libvirt_stat['results'][0]['stat']['dev'] != libvirt_stat['results'][1]['stat']['dev']
