# KVM/libvirt network configuration task
---
- name: Creating KVM/libvirt {{ network_name }} network bridge template & network
  block:

    - name: Creating KVM/libvirt {{ network_name }} network bridge template & network
      become: no
      template:
        src: ../templates/kvm-network-bridge.xml.j2
        dest: "{{ systemuserhome }}/kvm-{{ network_name }}-network-bridge.xml"
        owner: "{{ systemuser }}"
        group: "{{ systemuser }}"
        mode: 0644
      vars:
        network_name: "{{ kvm_network_name }}"
        bridge_interface: "{{ kvm_bridge_itf }}"
        uuid_seed: "OpenNext-{{ kvm_network_name }}"

    - name: Getting XML definition of KVM/libvirt {{ network_name }} network
      slurp:
        src: "{{ systemuserhome }}/kvm-{{ network_name }}-network-bridge.xml"
      register: xml_network

    - name: Creating KVM/libvirt {{ network_name }} network
      virt_net:
        command: define
        name: "{{ kvm_network_name }}"
        xml: "{{ xml_network['content'] | b64decode }}"
  when: ansible_libvirt_networks is defined and kvm_network_name not in ansible_libvirt_networks

- name: Autostarting KVM/libvirt {{ network_name }} network
  virt_net:
    autostart: yes
    name: "{{ kvm_network_name }}"

- name: Activating KVM/libvirt {{ network_name }} network
  virt_net:
    state: active
    name: "{{ kvm_network_name }}"
