# KVM/libvirt host configuration task
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Adding existing user {{ systemuser }} to group {{ libvirtgroup }}
  user:
    name="{{ systemuser }}"
    groups="{{ libvirtgroup }}"
    append=yes

- name: Making sure libvirt service is running
  service:
    name: "{{ libvirtservice }}"
    state: started

# Facts will be available as 'ansible_libvirt_networks'
- name: Gather facts about available networks in KVM/libvirt
  virt_net:
    command: facts

- include_tasks: ../tasks/kvm_network_configure.yml
  vars:
    network_name: "{{ kvm_prov_network_name }}"
    kvm_network_name: "{{ kvm_prov_network_name }}"
    kvm_bridge_itf: "{{ kvm_prov_bridge_itf }}"

- include_tasks: ../tasks/kvm_network_configure.yml
  vars:
    network_name: "{{ kvm_vms_network_name }}"
    kvm_network_name: "{{ kvm_vms_network_name }}"
    kvm_bridge_itf: "{{ kvm_vms_bridge_itf }}"

- name: Retrieving max free space mount point
  set_fact:
    max_free_mount: "{{ ansible_mounts | sort('size_available' | int) | last }}"

- name: Setting {{ libvirtvarpath }} destination to max free space zone
  set_fact:
    virt_dest: "{{ max_free_mount['mount'] }}"

- name: Getting filesystem informations about {{ libvirtvarpath }}
  stat:
    path: "{{ item }}"
    follow: yes
  register: libvirt_stat
  with_items:
    - "{{ libvirtvarpath }}"
    - "{{ virt_dest }}"

- name: Migrating {{ libvirtvarpath }} to {{ virt_dest }}
  block:

    - name: Stopping libvirt service
      service:
        name: "{{ libvirtservice }}"
        state: stopped

    - name: Moving over {{ libvirtvarpath }} to {{ virt_dest }}
      command: "mv {{ libvirtvarpath }} {{ virt_dest }}"

    - name: Re-creating {{ libvirtvarpath }} directory
      file:
        path: "{{ libvirtvarpath }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Bindmounting {{ virt_dest | regex_replace('/$', '') }}/{{ libvirtvarpath | basename }} onto {{ libvirtvarpath }}
      mount:
        path: "{{ libvirtvarpath }}"
        src: "{{ virt_dest | regex_replace('/$', '') }}/{{ libvirtvarpath | basename }}"
        opts: bind
        fstype: none
        state: mounted

    - name: Restarting libvirt service
      service:
        name: "{{ libvirtservice }}"
        state: started
  when: libvirt_stat['results'][0]['stat']['dev'] != libvirt_stat['results'][1]['stat']['dev']
