# Ironic VMs status retrieval task
---
- name: Getting status from register-helper utility agent
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ status_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
  register: registered_status
  until: registered_status.content_length | int > 3
  delay: 15
  retries: 8

- name: Fetching detailed informations from register-helper utility agent
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ details_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
    status_code: 200
  register: registered_machines
