# Ironic nodes status retrieval task
---
- fail: msg="Node name can not be empty"
  when: node_name is defined and node_name | length == 0

- name: Getting status from register-helper utility agent (by count)
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ status_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
  register: tmp_registered_status
  until: (tmp_registered_status.content_length | int > 3) and (tmp_registered_status.get('json', {}).keys() | length >= nodes_nb | default(1))
  delay: "{{ node_status_delay | default(15) }}"
  retries: "{{ node_status_retries | default(8) }}"
  when: node_name is undefined

- name: Storing status result (by count)
  set_fact:
    registered_status: "{{ tmp_registered_status }}"
  when: not tmp_registered_status.get('skipped', False)

- name: Getting status from register-helper utility agent (by name)
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ status_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
  register: tmp_registered_status
  until: (tmp_registered_status.content_length | int > 3) and (tmp_registered_status.get('json', {}).keys() | select('match', node_name) | list | length >= 1)
  delay: "{{ node_status_delay | default(15) }}"
  retries: "{{ node_status_retries | default(8) }}"
  when: node_name is defined

- name: Storing status result (by name)
  set_fact:
    registered_status: "{{ tmp_registered_status }}"
  when: not tmp_registered_status.get('skipped', False)

- name: Fetching detailed informations from register-helper utility agent
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ details_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
    status_code: 200
  register: registered_machines
