# Network interfaces from type selection task
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Selecting all interfaces
  set_fact:
    all_itfs: "{{ hostvars[inventory_hostname]['ansible_interfaces'] | map('replace', '-', '_') | list }}"
    all_required: "{{ select_all_itfs | default(false) | bool }}"

- name: Selecting IPv4 interfaces with {{ itf_type }} type
  set_fact:
    itfs: "{% set sel = [] %}{% for x in all_itfs %}{% if all_required or hostvars[inventory_hostname]['ansible_' + x]['type'] is match(itf_type) %}{% set l = sel.append(hostvars[inventory_hostname]['ansible_' + x]) %}{% endif %}{% endfor %}{{ sel | list }}"
