# Network Interface retrieval task
---
- name: Initializing search for IPv4 interface with {{ itf_type }} type
  set_fact:
    itfs: []

- name: Selecting IPv4 interface with {{ itf_type }} type
  set_fact:
    itfs: "{% set itfs = itfs + [hostvars[inventory_hostname]['ansible_' + item]] %}{{ itfs | list }}"
  when: hostvars[inventory_hostname]['ansible_' + item]['type'] is match(itf_type)
  with_items: "{{ hostvars[inventory_hostname]['ansible_interfaces'] | map('replace', '-', '_') | list }}"
