# Ansible facts dumping task
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setting destination facts directory
  set_fact:
    dest_fact_dir: "/etc/ansible/facts.d"

- name: Checking {{ dest_fact_dir }} directory
  stat:
    path: "{{ dest_fact_dir }}"
  register: fact_dir_exists

- name: Creating {{ dest_fact_dir }} directory
  become: yes
  file:
    path: "{{ dest_fact_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: yes
  when: not fact_dir_exists.stat.exists

- name: Setting destination facts file
  set_fact:
    dest_fact_file: "{{ dest_fact_dir }}/{{ facts_file }}.fact"
    dest_fact_dump: "{{ dest_fact_dir }}/{{ facts_file }}.dump"

- name: Checking existence of fact file
  stat:
    path: "{{ dest_fact_dir }}/{{ facts_file }}.fact"
  register: fact_file_status

- name: Dumping hostvars to {{ dest_fact_dump }}
  become: yes
  action: template src=../templates/dump_var_json.j2 dest="{{ dest_fact_dump }}"
  vars:
    myvar: "{{ hostvars | to_json | hostvars_filter([], ['^ansible_local']) }}"
  when: not fact_file_status.stat.exists or (force_update is defined and force_update | bool == True)

- name: Dumping selected hostvars to {{ dest_fact_file }}
  become: yes
  action: template src=../templates/dump_var_json.j2 dest="{{ dest_fact_file }}"
  vars:
    myvar: "{{ hostvars | to_json | hostvars_filter(keys_to_store) }}"
  when: not fact_file_status.stat.exists or (force_update is defined and force_update | bool == True)
