# Ironic VMs status retrieval task
---
- name: Getting status from register-helper utility agent
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ status_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
    status_code: 200
  register: registered_status
- name: Fetching detailed informations from register-helper utility agent
  uri:
    url: "http://{{ registration_ip }}:{{ registration_port }}/{{ details_uri }}"
    force_basic_auth: yes
    user: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('username', '') }}"
    password: "{{ clouds.get('clouds', {}).get('bifrost-admin', {}).get('auth', {}).get('password', '') }}"
    status_code: 200
  register: registered_machines
