# Tasks for configuring hostname
---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Checking dynamic hostname
  command: "hostname"
  changed_when: false
  register: hostname_result

- name: Updating /etc/hosts with {{ fqdn }} (Ubuntu)
  lineinfile:
    path: /etc/hosts
    backrefs: yes
    regexp: '^(\S+\s+)ubuntu(\s+.*)?$'
    line: '\1{{ fqdn }} {{ inventory_hostname }} ubuntu\2'
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution | lower == 'ubuntu' and is_host_to_be_modified

- name: Updating /etc/hosts with {{ fqdn }} (CentOS)
  lineinfile:
    path: /etc/hosts
    firstmatch: yes
    insertbefore: '^(\S+\s+)localhost(\s+.*)?$'
    line: '127.0.1.1   {{ fqdn }} {{ inventory_hostname }}'
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution | lower == 'centos' and is_host_to_be_modified

- name: Changing dynamic hostname to {{ fqdn }}
  command: "hostname {{ fqdn }}"
  when: is_host_to_be_modified and hostname_result.stdout != fqdn

- name: Removing ubuntu in /etc/hosts (Ubuntu)
  lineinfile:
    path: /etc/hosts
    backrefs: yes
    regexp: '^(.*)\s+ubuntu\s*(.*)?$'
    line: '\1\2'
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution | lower == 'ubuntu' and is_host_to_be_modified

- name: Updating /etc/hostname with {{ fqdn }}
  copy:
    dest: /etc/hostname
    content: '{{ fqdn }}'
    owner: root
    group: root
    mode: 0644
  when: is_host_to_be_modified
